# Site wide configuration

title: Quantum Leap
locale: en_US
description: Development, Smart Tools and Automation
logo: site-logo.png
teaser: line-teaser.jpg
search: true
url:

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Carlo Lobrano   
  avatar: bio-photo.jpg
  email: c.lobrano@gmail.com
  disqus-shortname:
  twitter: carlolobrano
  github: clobrano
  stackexchange: http://stackoverflow.com/users/1197008/carlo
  linkedin: carlolobrano
  instagram: carlo.lobrano
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
